version: "3.9"

services:
  web:
    image: aussidavid/monday_shareable_dashboard_backend
    build: .
    ports:
      - 8080:8080
    environment:
      HEADLESS: "true"
    cap_add:
      - SYS_ADMIN
